# Generated by Django 6.0.6 on 2026-07-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knowledge_point_id", models.CharField(max_length=64, unique=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                (
                    "parent_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("subject", models.CharField(max_length=32)),
                ("stage", models.CharField(max_length=64)),
                ("grade_range", models.JSONField(default=list)),
                ("path", models.JSONField(default=list)),
                ("version", models.CharField(default="2026.1", max_length=32)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["subject", "stage", "version", "enabled"],
                        name="resources_k_subject_51d054_idx",
                    ),
                    models.Index(
                        fields=["version", "code"],
                        name="resources_k_version_9bf2af_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"),
                        name="unique_knowledge_point_code_version",
                    )
                ],
            },
        ),
    ]
