# Generated by Django 6.0.6 on 2026-07-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgepoint",
            name="knowledge_point_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="knowledgepoint",
            constraint=models.UniqueConstraint(
                fields=("knowledge_point_id", "version"),
                name="unique_knowledge_point_id_version",
            ),
        ),
    ]
