# Generated by Django 6.0.6 on 2026-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_knowledgepoint_knowledge_point_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBankItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_question_id", models.CharField(max_length=64, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("school_bank", "School bank"),
                            ("exam_history", "Exam history"),
                            ("middle_exam_real", "Middle exam real"),
                            ("external_import", "External import"),
                            ("ai_generated", "AI generated"),
                        ],
                        max_length=32,
                    ),
                ),
                ("content_html", models.TextField()),
                ("answer_html", models.TextField()),
                ("analysis_html", models.TextField()),
                ("question_type", models.CharField(max_length=64)),
                ("difficulty", models.FloatField()),
                ("images", models.JSONField(default=list)),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="approved",
                        max_length=32,
                    ),
                ),
                (
                    "knowledge_point_version",
                    models.CharField(default="2026.1", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "knowledge_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="question_bank_items",
                        to="resources.knowledgepoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "bank_question_id"],
                "indexes": [
                    models.Index(
                        fields=["source", "audit_status"],
                        name="resources_q_source_507e31_idx",
                    ),
                    models.Index(
                        fields=["knowledge_point_version", "audit_status"],
                        name="resources_q_knowled_53aa91_idx",
                    ),
                    models.Index(
                        fields=["difficulty"], name="resources_q_difficu_c7ca36_idx"
                    ),
                ],
            },
        ),
    ]
