# Generated by Django 6.0.6 on 2026-07-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_questionbankitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_pack_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('target', models.CharField(choices=[('class', 'Class'), ('student', 'Student')], max_length=16)),
                ('target_ref_id', models.CharField(db_index=True, max_length=64)),
                ('knowledge_point_version', models.CharField(default='2026.1', max_length=32)),
                ('created_by', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_points', models.ManyToManyField(blank=True, related_name='practice_packs', to='resources.knowledgepoint')),
                ('questions', models.ManyToManyField(blank=True, related_name='practice_packs', to='resources.questionbankitem')),
            ],
            options={
                'ordering': ['-created_at', 'practice_pack_id'],
                'indexes': [models.Index(fields=['target', 'target_ref_id', 'status'], name='resources_p_target_c0457e_idx'), models.Index(fields=['created_by', 'status'], name='resources_p_created_a3e91a_idx'), models.Index(fields=['knowledge_point_version', 'status'], name='resources_p_knowled_8c21f2_idx')],
            },
        ),
    ]
