# Generated by Django 6.0.6 on 2026-07-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_practicepack'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_question_id', models.CharField(max_length=64, unique=True)),
                ('source_question_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('content_html', models.TextField()),
                ('answer_html', models.TextField()),
                ('analysis_html', models.TextField()),
                ('question_type', models.CharField(max_length=64)),
                ('difficulty', models.FloatField()),
                ('images', models.JSONField(default=list)),
                ('validation', models.JSONField(default=dict)),
                ('audit_status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=32)),
                ('knowledge_point_version', models.CharField(default='2026.1', max_length=32)),
                ('reviewer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('raw_request', models.JSONField(default=dict)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_question', to='resources.questionbankitem')),
                ('knowledge_points', models.ManyToManyField(blank=True, related_name='generated_questions', to='resources.knowledgepoint')),
            ],
            options={
                'ordering': ['-created_at', 'generated_question_id'],
                'indexes': [models.Index(fields=['audit_status', 'created_at'], name='resources_g_audit_s_049291_idx'), models.Index(fields=['knowledge_point_version', 'audit_status'], name='resources_g_knowled_092b9f_idx'), models.Index(fields=['source_question_id'], name='resources_g_source__9fcecc_idx')],
            },
        ),
    ]
