# Generated by Django 6.0.6 on 2026-07-14 16:26

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0005_generatedquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="WrongQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wrong_question_id", models.CharField(max_length=64, unique=True)),
                ("tenant_id", models.CharField(default="default", max_length=64)),
                ("student_id", models.CharField(max_length=64)),
                ("subject", models.CharField(max_length=32)),
                ("grade", models.CharField(max_length=32)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=students.models.wrong_question_upload_to,
                    ),
                ),
                (
                    "recognition_job_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("recognizing", "Recognizing"),
                            ("recognized", "Recognized"),
                            ("confirmed", "Confirmed"),
                            ("learning", "Learning"),
                            ("mastered", "Mastered"),
                        ],
                        default="uploaded",
                        max_length=32,
                    ),
                ),
                ("question", models.JSONField(default=dict)),
                ("knowledge_candidates", models.JSONField(default=list)),
                (
                    "knowledge_point_version",
                    models.CharField(default="2026.1", max_length=32),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_knowledge_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wrong_questions",
                        to="resources.knowledgepoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "wrong_question_id"],
            },
        ),
        migrations.CreateModel(
            name="ExplanationInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_id", models.CharField(max_length=64, unique=True)),
                ("tenant_id", models.CharField(default="default", max_length=64)),
                ("student_id", models.CharField(max_length=64)),
                ("current_step_index", models.PositiveIntegerField(default=0)),
                ("student_input", models.TextField(blank=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("hint", "Hint"),
                            ("check", "Check"),
                            ("explain", "Explain"),
                            ("summary", "Summary"),
                        ],
                        max_length=16,
                    ),
                ),
                ("response", models.JSONField(default=dict)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wrong_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanation_interactions",
                        to="students.wrongquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "interaction_id"],
            },
        ),
        migrations.CreateModel(
            name="PracticeAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_record_id", models.CharField(max_length=64, unique=True)),
                ("tenant_id", models.CharField(default="default", max_length=64)),
                ("student_id", models.CharField(max_length=64)),
                (
                    "knowledge_point_version",
                    models.CharField(default="2026.1", max_length=32),
                ),
                ("answer_text", models.TextField(blank=True)),
                ("is_correct", models.BooleanField()),
                ("used_seconds", models.PositiveIntegerField(default=0)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_answers",
                        to="resources.questionbankitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "answer_record_id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "student_id", "created_at"],
                        name="students_pr_tenant__d7611c_idx",
                    ),
                    models.Index(
                        fields=["question", "created_at"],
                        name="students_pr_questio_a7df5b_idx",
                    ),
                    models.Index(
                        fields=["knowledge_point_version", "created_at"],
                        name="students_pr_knowled_97f007_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        fields=("tenant_id", "student_id", "idempotency_key"),
                        name="students_pa_idempotency_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(default="default", max_length=64)),
                ("student_id", models.CharField(max_length=64)),
                (
                    "knowledge_point_version",
                    models.CharField(default="2026.1", max_length=32),
                ),
                ("mastery_rate", models.FloatField(default=0.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_masteries",
                        to="resources.knowledgepoint",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant_id", "student_id", "knowledge_point_id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "student_id", "updated_at"],
                        name="students_st_tenant__11918a_idx",
                    ),
                    models.Index(
                        fields=["knowledge_point_version", "mastery_rate"],
                        name="students_st_knowled_14988f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant_id",
                            "student_id",
                            "knowledge_point",
                            "knowledge_point_version",
                        ),
                        name="students_mastery_student_kp_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("mastery_rate__gte", 0.0), ("mastery_rate__lte", 1.0)
                        ),
                        name="students_mastery_rate_range",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="wrongquestion",
            index=models.Index(
                fields=["tenant_id", "student_id", "status", "created_at"],
                name="students_wr_tenant__4da0b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wrongquestion",
            index=models.Index(
                fields=["knowledge_point_version", "status"],
                name="students_wr_knowled_a04a8f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="wrongquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "uploaded",
                            "recognizing",
                            "recognized",
                            "confirmed",
                            "learning",
                            "mastered",
                        ),
                    )
                ),
                name="students_wq_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="wrongquestion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant_id", "student_id", "idempotency_key"),
                name="students_wq_idempotency_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="explanationinteraction",
            index=models.Index(
                fields=["tenant_id", "student_id", "wrong_question", "created_at"],
                name="students_ex_tenant__8093a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="explanationinteraction",
            index=models.Index(
                fields=["wrong_question", "current_step_index"],
                name="students_ex_wrong_q_c7885e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="explanationinteraction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mode__in", ("hint", "check", "explain", "summary"))
                ),
                name="students_explanation_mode_valid",
            ),
        ),
    ]
