param(
  [string]$BaseUrl = "https://token.zy-cjk.cn/v1",
  [string]$Model = "openai-compatible",
  [int]$TimeoutSeconds = 8,
  [string]$EnvPath = "",
  [switch]$NoPrompt
)

$ErrorActionPreference = "Stop"
try {
  [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
  $OutputEncoding = [Console]::OutputEncoding
} catch {
}

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
if (!$EnvPath) {
  $EnvPath = Join-Path $Root ".env"
}

function Convert-SecureStringToPlainText {
  param([System.Security.SecureString]$SecureValue)

  if (!$SecureValue -or $SecureValue.Length -eq 0) {
    return ""
  }
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureValue)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

function Read-EnvMap {
  param([string]$Path)

  $map = [ordered]@{}
  if (!(Test-Path -LiteralPath $Path)) {
    return $map
  }

  foreach ($rawLine in Get-Content -LiteralPath $Path) {
    $line = $rawLine.Trim()
    if (!$line -or $line.StartsWith("#") -or !$line.Contains("=")) {
      continue
    }
    $key, $value = $line.Split("=", 2)
    $key = $key.Trim().TrimStart([char]0xFEFF)
    if ($key -match "^[A-Za-z_][A-Za-z0-9_]*$") {
      $map[$key] = $value.Trim()
    }
  }
  return $map
}

function Quote-EnvValue {
  param([string]$Value)

  if ($null -eq $Value) {
    return ""
  }
  if ($Value -match "[`r`n]") {
    throw "Environment values must be single-line strings."
  }
  if ($Value -match "[#\s'`"]") {
    return '"' + ($Value -replace '\\', '\\' -replace '"', '\"') + '"'
  }
  return $Value
}

$envMap = Read-EnvMap $EnvPath
$envMap["CAMPUS_LLM_BASE_URL"] = $BaseUrl.TrimEnd("/")
$envMap["CAMPUS_LLM_MODEL"] = $Model
$envMap["CAMPUS_LLM_TIMEOUT_SECONDS"] = [string]$TimeoutSeconds

if (!$NoPrompt) {
  $secureKey = Read-Host "Enter CAMPUS_LLM_API_KEY (input hidden; leave blank to keep existing value)" -AsSecureString
  $plainKey = Convert-SecureStringToPlainText $secureKey
  if ($plainKey) {
    $envMap["CAMPUS_LLM_API_KEY"] = $plainKey
  } elseif (!$envMap.Contains("CAMPUS_LLM_API_KEY")) {
    $envMap["CAMPUS_LLM_API_KEY"] = ""
  }
} elseif (!$envMap.Contains("CAMPUS_LLM_API_KEY")) {
  $envMap["CAMPUS_LLM_API_KEY"] = ""
}

$orderedKeys = @(
  "CAMPUS_LLM_BASE_URL",
  "CAMPUS_LLM_API_KEY",
  "CAMPUS_LLM_MODEL",
  "CAMPUS_LLM_TIMEOUT_SECONDS",
  "CAMPUS_P3_BASE_URL",
  "CAMPUS_P3_SERVICE_ID",
  "CAMPUS_P3_AUTH_TOKEN",
  "CAMPUS_P3_TIMEOUT_SECONDS",
  "CAMPUS_P2_SQLITE_PATH",
  "CAMPUS_AUTH_REQUIRED",
  "CAMPUS_P2_AUTH_TOKEN",
  "CAMPUS_DEFAULT_TENANT_ID",
  "CAMPUS_DEFAULT_TEACHER_ID",
  "CAMPUS_DEFAULT_STUDENT_ID",
  "CAMPUS_IDENTITY_DIRECTORY_REQUIRED",
  "CAMPUS_IDENTITY_DIRECTORY_PATH",
  "VITE_CAMPUS_TENANT_ID",
  "VITE_CAMPUS_TEACHER_ID",
  "VITE_CAMPUS_STUDENT_ID",
  "VITE_CAMPUS_DEMO_AUTH_TOKEN",
  "P3_DATABASE_ENGINE",
  "P3_SQLITE_PATH"
)

$defaults = [ordered]@{
  CAMPUS_P3_BASE_URL = "http://127.0.0.1:8103"
  CAMPUS_P3_SERVICE_ID = "p2-service"
  CAMPUS_P3_AUTH_TOKEN = ""
  CAMPUS_P3_TIMEOUT_SECONDS = "5"
  CAMPUS_P2_SQLITE_PATH = "data/p2_demo.sqlite3"
  CAMPUS_AUTH_REQUIRED = "false"
  CAMPUS_P2_AUTH_TOKEN = ""
  CAMPUS_DEFAULT_TENANT_ID = "demo_school"
  CAMPUS_DEFAULT_TEACHER_ID = "teacher_demo"
  CAMPUS_DEFAULT_STUDENT_ID = "student_demo"
  CAMPUS_IDENTITY_DIRECTORY_REQUIRED = "false"
  CAMPUS_IDENTITY_DIRECTORY_PATH = ""
  VITE_CAMPUS_TENANT_ID = "demo_school"
  VITE_CAMPUS_TEACHER_ID = "teacher_demo"
  VITE_CAMPUS_STUDENT_ID = "student_demo"
  VITE_CAMPUS_DEMO_AUTH_TOKEN = ""
  P3_DATABASE_ENGINE = "sqlite"
  P3_SQLITE_PATH = "data/p3_demo.sqlite3"
}

foreach ($key in $defaults.Keys) {
  if (!$envMap.Contains($key)) {
    $envMap[$key] = $defaults[$key]
  }
}

$lines = @(
  "# Campus-System local configuration."
  "# Generated by scripts/configure_llm_env.ps1. Do not commit this file."
  ""
)
foreach ($key in $orderedKeys) {
  if ($envMap.Contains($key)) {
    $lines += "$key=$(Quote-EnvValue ([string]$envMap[$key]))"
  }
}
foreach ($key in $envMap.Keys) {
  if ($orderedKeys -notcontains $key) {
    $lines += "$key=$(Quote-EnvValue ([string]$envMap[$key]))"
  }
}

$envDir = Split-Path -Parent $EnvPath
if ($envDir -and !(Test-Path -LiteralPath $envDir)) {
  New-Item -ItemType Directory -Force -Path $envDir | Out-Null
}
[System.IO.File]::WriteAllLines($EnvPath, $lines, [System.Text.UTF8Encoding]::new($false))

$keyConfigured = $envMap.Contains("CAMPUS_LLM_API_KEY") -and [string]$envMap["CAMPUS_LLM_API_KEY"]
Write-Host "Wrote local configuration: $EnvPath"
Write-Host "llm_base_url=$($envMap["CAMPUS_LLM_BASE_URL"])"
Write-Host "llm_model=$($envMap["CAMPUS_LLM_MODEL"])"
Write-Host "llm_api_key_configured=$([bool]$keyConfigured)"
